### ISSUE TITLE
[DOC] Demonstrate use of kai.existingSecret

### ISSUE THREAD

**Issue by flickerfly** [anchore/kai#58]
**What happened**:

I tried to use the kai.existingSecret key in the config. It only told me to create one. I don't know what that secret should look like.

**What you expected to happen**:

I expected to be given some information about what the contents of the kai.existingSecret's k8s secret should be.

**How to reproduce it (as minimally and precisely as possible)**:

Using just the documentation, determine how to setup an existingSecret to pass anchore enterprise credentials to kai.

**Comment by flickerfly** [comment]
Oh, I found it now. 
```
apiVersion: v1
kind: Secret
metadata:
  name: kai-anchore-password
type: Opaque
stringData:
  KAI_ANCHORE_PASSWORD: foobar
```
